### ISSUE TITLE
Error while starting the API

### ISSUE THREAD

**Issue by MarcoBuster** [ALCC01/ClassevivaAPI#4]
Hello, while I try to **start** the **API**, using `sudo npm start`, it's returns me this **errors**:

```
marcobuster@vps280105:~/ClassevivaAPI$ sudo npm start

> ClassevivaAPI@0.0.0 start /home/marcobuster/ClassevivaAPI
> node ./app.js

module.js:328
    throw err;
    ^

Error: Cannot find module './config.json'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/marcobuster/ClassevivaAPI/app.js:5:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

npm ERR! Linux 4.4.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! ClassevivaAPI@0.0.0 start: `node ./app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ClassevivaAPI@0.0.0 start script 'node ./app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ClassevivaAPI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ClassevivaAPI
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ClassevivaAPI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/marcobuster/ClassevivaAPI/npm-debug.log
marcobuster@vps280105:~/ClassevivaAPI$ 
```

**Comment by ALCC01** [comment]
As I already told you via Telegram, you need to create a conifg.json file (see the default config.dist.json file).
